version: '2.2'

networks:
  keycloak:
services:

  radarbase-postgresql:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rbkeycloak
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD='${POSTGRES_PASSWORD}' psql -U '${POSTGRES_USER}' rbkeycloak -l || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3

  radarbase-keycloak:
    build: .
    image: radarbase/keycloak:4.5.0.Final
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER : ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: radarbase-postgresql
      DB_DATABASE: rbkeycloak
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./theme/ucl:/opt/jboss/keycloak/themes/ucl
    depends_on:
      - radarbase-postgresql
    restart: always
